#ifndef OBJECT_ROTLIFT_H
#define OBJECT_ROTLIFT_H 1

extern Vtx object_rotliftVtx_000000[];
extern Gfx gDekuMoonDungeonRotatingPlatformsDL[];
extern u64 gDekuMoonDungeonRotatingPlatformsWoodBarkTLUT[];
extern u64 gDekuMoonDungeonRotatingPlatformsWoodBarkTex[];
extern u64 gDekuMoonDungeonRotatingPlatformsWoodTex[];
extern AnimatedMatTexScrollParams gDekuMoonDungeonRotatingPlatformsUnusedTexAnimTexScrollParams_001F90[];
extern AnimatedMaterial gDekuMoonDungeonRotatingPlatformsUnusedTexAnim[];
extern CamData gDekuMoonDungeonRotatingPlatformsColCamDataList[];
extern SurfaceType gDekuMoonDungeonRotatingPlatformsColSurfaceType[];
extern CollisionPoly gDekuMoonDungeonRotatingPlatformsColPolygons[];
extern Vec3s gDekuMoonDungeonRotatingPlatformsColVertices[];
extern CollisionHeader gDekuMoonDungeonRotatingPlatformsCol;
extern Vtx object_rotliftVtx_0021C0[];
extern Gfx gDekuMoonDungeonRotatingSpikesDL[];
extern u64 gDekuMoonDungeonRotatingSpikesWoodBarkTLUT[];
extern u64 gDekuMoonDungeonRotatingSpikesWoodBarkTex[];
extern u64 gDekuMoonDungeonRotatingSpikesWoodTex[];
extern AnimatedMatTexScrollParams gDekuMoonDungeonRotatingSpikesUnusedTexAnimTexScrollParams_004A00[];
extern AnimatedMaterial gDekuMoonDungeonRotatingSpikesUnusedTexAnim[];
extern CamData gDekuMoonDungeonRotatingSpikesColCamDataList[];
extern SurfaceType gDekuMoonDungeonRotatingSpikesColSurfaceType[];
extern CollisionPoly gDekuMoonDungeonRotatingSpikesColPolygons[];
extern Vec3s gDekuMoonDungeonRotatingSpikesColVertices[];
extern CollisionHeader gDekuMoonDungeonRotatingSpikesCol;
#endif
