#ifndef OBJECT_HUNSUI_H
#define OBJECT_HUNSUI_H 1

extern Vtx object_hunsuiVtx_000000[];
extern Gfx object_hunsui_DL_000220[];
extern u64 object_hunsui_Tex_0003E0[];
extern AnimatedMatTexScrollParams object_hunsui_Matanimheader_000BF0TexScrollParams_000BE0[];
extern AnimatedMatTexScrollParams object_hunsui_Matanimheader_000BF0TexScrollParams_000BE8[];
extern AnimatedMaterial object_hunsui_Matanimheader_000BF0[];
extern CamData object_hunsui_Colheader_000C74CamDataList[];
extern SurfaceType object_hunsui_Colheader_000C74SurfaceType[];
extern CollisionPoly object_hunsui_Colheader_000C74Polygons[];
extern Vec3s object_hunsui_Colheader_000C74Vertices[];
extern CollisionHeader object_hunsui_Colheader_000C74;
extern Vtx object_hunsuiVtx_000CA0[];
extern Gfx object_hunsui_DL_000EC0[];
extern u64 object_hunsui_Tex_001078[];
extern AnimatedMatTexScrollParams object_hunsui_Matanimheader_001888TexScrollParams_001878[];
extern AnimatedMatTexScrollParams object_hunsui_Matanimheader_001888TexScrollParams_001880[];
extern AnimatedMaterial object_hunsui_Matanimheader_001888[];
extern CamData object_hunsui_Colheader_00190CCamDataList[];
extern SurfaceType object_hunsui_Colheader_00190CSurfaceType[];
extern CollisionPoly object_hunsui_Colheader_00190CPolygons[];
extern Vec3s object_hunsui_Colheader_00190CVertices[];
extern CollisionHeader object_hunsui_Colheader_00190C;
#endif
