#ifndef OBJECT_KEIKOKU_DEMO_H
#define OBJECT_KEIKOKU_DEMO_H 1

extern Vtx object_keikoku_demoVtx_000000[];
extern Gfx gKeikokuDemoFloorEmptyDL[];
extern Gfx gKeikokuDemoFloorDL[];
extern u64 gKeikokuDemoYellowFlowersOnGrassTex[];
extern u64 gKeikokuDemoFallLeavesOnGrassTex[];
extern CamData gKeikokuDemoFloorColCamDataList[];
extern SurfaceType gKeikokuDemoFloorColSurfaceType[];
extern CollisionPoly gKeikokuDemoFloorColPolygons[];
extern Vec3s gKeikokuDemoFloorColVertices[];
extern CollisionHeader gKeikokuDemoFloorCol;
extern Vtx object_keikoku_demoVtx_001CD0[];
extern Gfx gKeikokuDemoTallTreeWithRootBaseEmptyDL[];
extern Gfx gKeikokuDemoTallTreeWithRootBaseDL[];
extern Vtx object_keikoku_demoVtx_002BE0[];
extern Gfx gKeikokuDemoTallTreeCutEmptyDL[];
extern Gfx gKeikokuDemoTallTreeCutDL[];
extern Vtx object_keikoku_demoVtx_0032C0[];
extern Gfx gKeikokuDemoTallTreeStraightEmptyDL[];
extern Gfx gKeikokuDemoTallTreeStraightDL[];
extern u64 gKeikokuDemoTreeLeavesTex[];
extern u64 gKeikokuDemoTreeCutEndGrainTex[];
extern u64 gKeikokuDemoCloverEdgeTex[];
extern u64 gKeikokuDemoCloverTopTex[];
extern u64 gKeikokuDemoDarkMossyBarkTex[];
extern u64 gKeikokuDemoDarkGreenMossTex[];
extern u64 gKeikokuDemoBrightMossyBarkTex[];
extern u64 gKeikokuDemoDirtWallTex[];
extern u64 gKeikokuDemoTreeWallBackdropTex[];
extern u64 gKeikokuDemoHangingMossTex[];
extern u64 gKeikokuDemoStumpRingsDarkTex[];
extern u64 gKeikokuDemoStumpRingsPinkTex[];
extern u64 gKeikokuDemoTreeCutEndGrain2Tex[];
extern u64 gKeikokuDemoYellowFlowersOnGrass2Tex[];
extern u64 gKeikokuDemoFallLeavesOnGrass2Tex[];
extern u64 gKeikokuDemoYoungerBarkTex[];
extern u64 gKeikokuDemoWrinkledBarkTex[];
extern u64 gKeikokuDemoGreenSludgeTex[];
extern u64 gKeikokuDemoWhiteYellowArtifactTex[];
extern u64 gKeikokuDemoDullYellowFlowersOnGrassTex[];
#endif
